---
apiVersion: garden.io/v0
kind: Module
type: helm
name: service-7

repositoryUrl: 'ssh://git@github.com/nilium/dummy-redis#main'
allowPublish: false
releaseName: service-7
namespace: ${environment.namespace}

serviceResource:
  containerName: redis
  kind: StatefulSet
  name: service-7

values:
  image:
    pullPolicy: IfNotPresent
