---
apiVersion: garden.io/v0
kind: Module
type: helm
name: service-5

repositoryUrl: 'ssh://git@github.com/nilium/dummy-redis#main'
allowPublish: false
releaseName: service-5
namespace: ${environment.namespace}

serviceResource:
  containerName: redis
  kind: StatefulSet
  name: service-5

values:
  image:
    pullPolicy: IfNotPresent
    repository: ${modules.build-5-image.outputs.deployment-image-name}
    tag: ${modules.build-5.version}
