---
apiVersion: garden.io/v0
kind: Module
type: exec
name: build-3

repositoryUrl: 'ssh://git@github.com/nilium/dummy-redis#main'

include:
  - Dockerfile
  - Makefile

exclude:
  - .helmignore
  - templates/**/*
  - Chart.yml
  - values.yaml

build:
  command: [make, docker-build, NAME=service-3]

---
apiVersion: garden.io/v0
kind: Module
type: container
name: build-3-image

build:
  dependencies:
    - name: build-3

include: [Dockerfile]
dockerfile: Dockerfile
allowPublish: false

buildArgs:
  SERVICE_NAME: service-3
  BUILD: ${modules.build-3.version}
